stages:
  - build

build:
  stage: build
  image: golang:1.11.4
  before_script:
  script:
    # Compile and name the binary as `hello`
    - go build -o hello
    # Execute the binary
    - ./hello  